apiVersion: v1
kind: Pod
metadata:
  name: homework01
  namespace: homework
  labels:
    app: init
spec:
  initContainers:
  - name: init-container
    image: busybox
    command: ["/bin/sh", "-c", "echo 'Its works!' > /init/index.html"]
    volumeMounts:
    - name: homework01
      mountPath: /init
  containers:
  - name: web-server
    image: nginx
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: homework01
      mountPath: /homework
    - name: nginx-config-volume
      mountPath: /etc/nginx/conf.d
      readOnly: true
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh", "-c", "rm -f /homework/index.html"]
  volumes:
  - name: homework01
    emptyDir: {}
  - name: nginx-config-volume
    configMap:
      name: nginx-config
  terminationGracePeriodSeconds: 1
  dnsPolicy: Default